#!/bin/bash

# Add custom host entries to /etc/hosts
echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts

# Restart the network service to apply the changes
systemctl restart networking.service
